Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/carts_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/*' 
    - 'spec/requests/*'

AllCops:
  Exclude:
    - 'bin/bundle'