version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "bin/rails db:create db:migrate && bundle exec rails s -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/store_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    volumes:
      - .:/rails

  test:
    build: .
    command: bash -c "bin/rails db:create db:schema:load && bundle exec rspec"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/store_test
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: test
    volumes:
      - .:/rails

volumes:
  postgres_data:
  redis_data:
